<template>
   <div class="fade-in-top">
    <el-card class="box-card">
        <el-input placeholder="username" v-model="username"></el-input>
        <el-input placeholder="password" v-model="password"></el-input>
    <el-button type="primary" round  v-on:click="signup">signup</el-button>
    <el-button type="danger" round v-on:click="login">signin</el-button>
    </el-card>
   </div>
</template>
    

<script>
import router from '../router'
export default {
  name : 'Login',
  data(){
    return {
      username:'',
      password:''
    }
  },
  methods:{
    signup : function(){
      let user = this.username;
      let pass  = this.password;
      axios.post('http://localhost:3000/api/signup',{username:user,password:pass})
      .then(response=>{
        console.log(response.data.data)
        
      })
    },

    login : function(){
      let user = this.username;
      let pass = this.password;
      console.log('sudah masuk')
      axios.post('http://localhost:3000/api/signin',{username:user,password:pass})
      .then(response=>{
        console.log(response.data.token)
        let token = response.data.token
        localStorage.setItem('token',token)
        router.push({name:'HomeRoute'})
      })
      .catch(err=>{
        console.log(err)
      })
    }
  }
}
</script>


<style scoped>
    .box-card{
        margin : 0px 100px 0px 100px
    }

    .fade-in-top {
	-webkit-animation: fade-in-top 0.6s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
	        animation: fade-in-top 0.6s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
    }

    /* ----------------------------------------------
 * Generated by Animista on 2017-12-26 2:54:7
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in-top
 * ----------------------------------------
 */
@-webkit-keyframes fade-in-top {
  0% {
    -webkit-transform: translateY(-50px);
            transform: translateY(-50px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    opacity: 1;
  }
}
@keyframes fade-in-top {
  0% {
    -webkit-transform: translateY(-50px);
            transform: translateY(-50px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    opacity: 1;
  }
}

</style>
